name: Teams
main: org.plugin.teams.Teams
version: 1.0.0
author: Denis496
api-version: "1.21"
description: Team management plugin
softdepend: [PlayerStats, PlaceholderAPI, ChatPlugin]
libraries:
  - com.zaxxer:HikariCP:5.0.1
  - mysql:mysql-connector-java:8.0.33

commands:
  team:
    description: Main team management command
    usage: /<command> help
    aliases: [t, teams]

permissions:
  teams.use:
    description: Allows basic team commands
    default: true
  teams.admin:
    description: Administrative permissions
    default: op
  teams.bypass.playtime:
    description: Bypass playtime requirements
    default: op